title : Elementary - 极简风格博客
name: '松子腹地-谨防松鼠'
description: '过得糟糕的人难以改变自己的现状，却总希望将来的人过得更好。一面是消极的自毁倾向，一面是积极的人性光辉。​'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: 我的其他页面
featured_posts:
  - url: 'https://www.firehomework.ys168.com'
    title: '我的网盘'

collections:
  news:
    title: 更新日志(施工中)
    default_open: true
    output: true
  posts:
    title: 所有文章(点击标签分类筛选)
    default_open: false
    output: true
  evolve:
    title: 进化专题(NEW!)
    default_open: true
    output: true
  notes:
    title: 个人学习随记
    default_open: false
    output: true

# set collections and plugins dir, to make me migrate my blog easily.
source              : .
destination         : ./_site
collections_dir     : collections
plugins_dir         : src/_plugins # takes an array of strings and loads plugins in that order
layouts_dir         : src/_layouts
data_dir            : src/_data
includes_dir        : src/_includes
sass:
  sass_dir          : src/_sass

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title
  - scope:
      type: evolve
    values:
      title: Evolve
      permalink: /evolve/:title
  - scope:
      type: notes
    values:
      title: Notes
      permalink: /notes/:title

plugins:
  - jekyll-sitemap
